tabWidth: 2
useTabs: false
overrides:
  - files:
      - '*.yaml'
      - '*.yml'
    options:
      singleQuote: false
  - # json with comments
    files:
      - '.vscode/*.json'
      - 'scripts/*.json'
      - 'tsconfig.json'
    options:
      parser: json5
      quoteProps: preserve
      singleQuote: false
  - files:
      - '*.md'
    options:
      proseWrap: always
semi: true
singleQuote: true
