# alternative KISS pipeline to bloated ci.yml, modeled after vscode-ansible one.
name: npm

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: "1" # make mocha output colorful
  # https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/
  WSLENV: FORCE_COLOR:GITHUB_PATH/p

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: ${{ matrix.name || format('{0} ({1})', matrix.npm-target, matrix.os) }}
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell || 'bash'}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        npm-target:
          - test
        upload-artifact:
          - false
        name:
          - false
        include:
          - name: test (wsl)
            # runner does not support running container
            npm-target: test-without-ee
            # https://github.com/actions/virtual-environments/issues/5151
            os: windows-2019
            shell: "wsl-bash {0}"
          - name: test (macos)
            os: macos-11
            # runner does not support running container
            npm-target: test-without-ee

    steps:
      - name: Disable autocrlf
        if: "contains(matrix.os, 'windows')"
        run: |-
          git config --global core.autocrlf false
          git config --global core.eol lf
        shell: bash # <-- keep it here to avoid using default shell

      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/setup-wsl
      - name: Activate WSL
        if: "contains(matrix.shell, 'wsl')"
        uses: Vampire/setup-wsl@v1
        with:
          # we want to load user profile
          # https://github.com/Vampire/setup-wsl#wsl-shell-command
          wsl-shell-command: "bash -i -euo pipefail"

      - name: Use NodeJS v16
        # as Windows executables are exposed inside WSL at top of PATH, we
        # would end with broken npm script in PATH on wsl.
        if: "!contains(matrix.shell, 'wsl')"
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Run ./tools/test-setup.sh
        run: ./tools/test-setup.sh

      - name: npm run compile
        run: npm run compile

      - name: npm run ${{ matrix.npm-target }}
        run: npm run ${{ matrix.npm-target }}

  check: # This job does nothing and is only used for the branch protection
    if: always()
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
