# alternative KISS pipeline to bloated ci.yml, modeled after vscode-ansible one.
name: task

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: "1" # make mocha output colorful
  # https://docs.github.com/en/actions/learn-github-actions/environment-variables
  # https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/
  WSLENV: CI:FORCE_COLOR:GITHUB_ACTION:GITHUB_ACTION_PATH/p:GITHUB_ACTION_REPOSITORY:GITHUB_WORKFLOW:GITHUB_WORKSPACE/p:GITHUB_PATH/p

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    env:
      # to expose matrix job name to steps, which is not possible with expansions
      JOB_NAME: ${{ matrix.name || matrix.task-name }}
    name: ${{ matrix.name || matrix.task-name }}
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    defaults:
      run:
        shell: ${{ matrix.shell || 'bash'}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - "12"
        task-name:
          # - vscode
          # - test-node12
          # - test-node14
          - test-node16
        upload-artifact:
          - false
        name:
          - false
        include:
          # - name: lint
          #   task-name: lint
          # - name: docs
          #   task-name: docs
          - name: test (wsl)
            # runner does not support running container
            task-name: test-without-ee
            # https://github.com/actions/virtual-environments/issues/5151
            # keep in mind than on 2022, wsl2 is default but it does not work
            # on GHA runners. So as part of installation you need to run
            # `wsl --set-default-version 2`
            os: windows-2022
            shell: "wsl-bash {0}"
          # - name: test (macos)
          #   os: macos-11
          #   # runner does not support running container
          #   task-name: test-without-ee

    steps:
      - name: Show windows version
        if: "contains(matrix.os, 'windows')"
        run: systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
        shell: cmd

      - name: Disable autocrlf
        if: "contains(matrix.os, 'windows')"
        run: |-
          git config --global core.autocrlf false
          git config --global core.eol lf
        shell: bash # <-- keep it here to avoid using default shell

      # https://github.com/marketplace/actions/setup-wsl
      - name: Activate WSL
        if: "contains(matrix.shell, 'wsl')"
        uses: Vampire/setup-wsl@v1.3.0
        with:
          # we want to load user profile
          # https://github.com/Vampire/setup-wsl#wsl-shell-command
          wsl-shell-command: "bash -i -euo pipefail"
          additional-packages:
            curl
            git
            make
            nodejs
            python3-dev
            python3-pip
            python3-venv
            qemu-user-static
            xvfb

      - name: Determine working-directory
        id: wsl
        if: "contains(matrix.shell, 'wsl')"
        # mv cannot be used on wsl to move the workspace from the /mnt mount
        # into ~/ as this will produce a "permission denied" error, we copy.
        shell: pwsh
        run: |
          $wsl_home=wsl --cd ~ --exec wslpath -w .;
          echo "$wsl_home";
          mkdir -p "$wsl_home\ws";
          mklink -D ws "$wsl_home\ws";
          echo "::set-output name=working-directory::$wsl_home\ws"
        # set -euxo pipefail
        # pwd
        # export PROJECT=`basename $GITHUB_WORKSPACE`
        # mkdir -p ~/$PROJECT
        # WIN_PATH=$(wslpath -w $HOME/$PROJECT)
        # echo PROJECT=$PROJECT

      # WARNING: GITHUB_WORKSPACE is hardcoded and we cannot modify it. The
      # runner is keeping this folder open so we cannot touch it (replace)
      # actions/checks does not allow you to write anywhere outside workspace
      # but we can create symlink inside it, tricking it to checkput on
      # different location.
      - uses: actions/checkout@v3
        with:
          # that is the symlinked folder that goes into linux partition:
          path: ws

      - name: Enable caching
        if: "!contains(matrix.shell, 'wsl')"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/npm
            ~/.cache/pip
            ~/.nvm/.cache
            ~/Library/Caches/pip
          key: >
            ${{ runner.os }}-${{ matrix.task-name }}-${{ hashFiles(
            'package.json',
            'package-lock.json',
            '.config/requirements.txt'
            ) }}

      - name: Install Task
        if: "!contains(matrix.shell, 'wsl')"
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Task (wsl)
        if: "contains(matrix.shell, 'wsl')"
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          task --version

      - name: WSL Magic 🎲
        if: "contains(matrix.shell, 'wsl')"
        working-directory: ${{ steps.wsl.outputs.working-directory }}"
        # mv cannot be used on wsl to move the workspace from the /mnt mount
        # into ~/ as this will produce a "permission denied" error, we copy.
        run: |
          set -euxo pipefail
          cd ~/ws
          pwd
          ls -la
        # pwd
        # export PROJECT=`basename $GITHUB_WORKSPACE`
        # mkdir -p $PROJECT
        # WIN_PATH=$(wslpath -w $HOME/$PROJECT)
        # echo PROJECT=$PROJECT
        # cd ..
        # # time cp -rp $GITHUB_WORKSPACE $HOME
        # # cd ~/$PROJECT
        # # git status
        # ls -la .
        # echo "::set-output name=working-directory::$WIN_PATH"

      - name: Dump node version into .nvmrc file
        # save node version in .nvmrc file by looking for a pattern like
        # node12 in job name. If pattern is not found it uses 'current' alias
        if: "!contains(matrix.shell, 'wsl')"
        run: >
          python3 -c 'import os, re;
          v = re.search("node(\d+)", os.environ.get("JOB_NAME", "")) or ["", "current"];
          print(v[1])' > .nvmrc

      - name: Use node
        # as Windows executables are exposed inside WSL at top of PATH, we
        # would end with broken npm script in PATH on wsl.
        if: "!contains(matrix.shell, 'wsl')"
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install task inside WSL
        if: "contains(matrix.shell, 'wsl')"
        run: |
          mkdir -p ~/.local/bin
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
          echo $PATH
          command -v task
          pwd
        working-directory: ${{ steps.wsl.outputs.working-directory }}"

      - run: task setup

      - name: task ${{ matrix.task-name }}
        run: task -v ${{ matrix.task-name }}

  check: # This job does nothing and is only used for the branch protection
    if: always()
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
