# This workflow tests if current language-server change breaks vscode-ansible
# extension by running extension tests with it.
name: vscode

on:
  pull_request:
  workflow_call:

jobs:
  ui-test:
    name: devel-vscode-ansible
    runs-on: ubuntu-latest
    steps:

      - name: Checkout ansible-language-server
        uses: actions/checkout@v2

      - name: Checkout vscode-ansible
        uses: actions/checkout@v2
        with:
          repository: ansible/vscode-ansible
          path: vscode-ansible
          # We will later move this folder to ../ due to below bug:
          # https://github.com/actions/checkout/issues/197

      - name: Configure node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Inject unreleased ansible-language-server into vscode-ansible extension
        # do not try to use command below as vsce package is unable to work with symlinked modules:
        # npm install --save ../ansible-language-server
        run: |
          set -ex
          mv vscode-ansible ..

          # workaround to sync the latest version of ansible-language-server
          # in the vscode-ansible package.json to avoid npm related failures while vsce packaging
          python tools/version_sync.py

          task setup

          pushd ../vscode-ansible
          task build
          rm -rf node_modules/@ansible/ansible-language-server
          rm -rf out/server/src/*
          cp -r ../ansible-language-server node_modules/@ansible/ansible-language-server
          npm ls
          # npm install --save ../ansible-language-server
          task package
          # we need to bring vsix artifact inside workspace
          cp *.vsix ../ansible-language-server/

      - name: Publish vsix artifact
        if: ${{ github.event.number }}
        uses: actions/upload-artifact@v3
        with:
          name: ansible-extension-from-pr-${{ github.event.number }}.vsix
          # this action cannot archive artifacts from outside workspace "../"
          # https://github.com/actions/upload-artifact/issues/246
          path: ansible-*.vsix
          retention-days: 15

      - name: Run test-ui with vscode-ansible
        uses: GabrielBB/xvfb-action@v1
        with:
          run: sh -c "task test-ui && cp *.vsix ../ansible-language-server/"
          working-directory: ../vscode-ansible

      - name: Run test-e2e with vscode-ansible
        uses: GabrielBB/xvfb-action@v1
        with:
          run: sh -c "task test-e2e && cp *.vsix ../ansible-language-server/"
          working-directory: ../vscode-ansible
