# This workflow tests if current language-server change breaks vscode-ansible
# extension by running extension tests with it.
name: vscode

on:
  pull_request:
  workflow_call:

jobs:
  ui-test:
    name: >-
      test:ui
    runs-on: ubuntu-latest
    steps:

      - name: Checkout ansible-language-server
        uses: actions/checkout@v2

      - name: Checkout vscode-ansible
        uses: actions/checkout@v2
        with:
          repository: ansible/vscode-ansible
          path: vscode-ansible
          # We will later move this folder to ../ due to below bug:
          # https://github.com/actions/checkout/issues/197

      - name: Configure node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Compile language server
        run: npm ci && npm run compile

      - name: Link ansible-language-server into vscode-ansible
        run: |
          set -ex
          mv vscode-ansible ..
          pushd ../vscode-ansible
          npm link --save ../ansible-language-server
          npm ls --depth=0 --link=true
          popd

      - name: >-
          Run test-ui with vscode-ansible
        uses: GabrielBB/xvfb-action@v1
        with:
          run: >-
            npm run test-ui
          working-directory: ../vscode-ansible
