# This workflow tests if current language-server change breaks vscode-ansible
# extension by running extension tests with it.
name: vscode

on:
  pull_request:
  workflow_call:

jobs:
  ui-test:
    name: >-
      test:ui
    runs-on: ubuntu-latest
    steps:

      - name: Checkout ansible-language-server
        uses: actions/checkout@v2

      - name: Checkout vscode-ansible
        uses: actions/checkout@v2
        with:
          repository: ansible/vscode-ansible
          path: vscode-ansible
          # We will later move this folder to ../ due to below bug:
          # https://github.com/actions/checkout/issues/197

      - name: Configure node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Inject unreleased ansible-language-server into vscode-ansible extension
        # do not try to use command below as vsce package is unable to work with symlinked modules:
        # npm install --save ../ansible-language-server
        run: |
          set -ex
          mv vscode-ansible ..
          pushd ../vscode-ansible
          npm ci  # Install vscode-ansible dependencies
          rm -rf node_modules/@ansible/ansible-language-server
          cp -r ../ansible-language-server node_modules/@ansible/ansible-language-server
          npm ls
          # npm install --save ../ansible-language-server
          npm run package

      - name: >-
          Run test-ui with vscode-ansible
        uses: GabrielBB/xvfb-action@v1
        with:
          run: >-
            npm run test-ui
          working-directory: ../vscode-ansible
